Spring boot criteria- query usage. Added ability to search books by parameters
YaroslavRadevychVynnytskyi/book-store pull request #22
Opened 2024-02-14 09:14 UTC by YaroslavRadevychVynnytskyi

2024-02-14 14:16 UTC, okuzan requested changes

2024-02-14 14:16 UTC, okuzan commented on src/main/java/application/bookstore/repository/book/BookSpecificationProviderManager.java
> +                .filter(p -> p.getKey().equals(key))
avoid short one letter naming even in stream chains, readability is more important that a second you save not writing out that full name

2024-02-14 14:16 UTC, okuzan commented on src/main/java/application/bookstore/repository/book/spec/TitleSpecificationProvider.java
> +                root.get("title").in(Arrays.stream(params).toArray());
let's extract this literal to a constant

2024-02-15 12:08 UTC, MentorMA requested changes

2024-02-15 12:08 UTC, MentorMA commented on src/main/java/application/bookstore/repository/book/BookSpecificationBuilder.java
> +                    .getSpecificationProvider("author")
For strings you can use constants and I see you already have constant author and title in other classes

2024-02-15 18:14 UTC, MentorMA requested changes

2024-02-15 18:14 UTC, MentorMA commented on src/main/java/application/bookstore/repository/book/BookSpecificationBuilder.java
> +    private static final String AUTHOR = "author";
You already have these constants in SpecificationProvider classes, don`t duplicate code

2024-02-16 10:01 UTC, merged