Added CustomGlobalExceptionHandler class and validation for existing DTO classes
YaroslavRadevychVynnytskyi/book-store pull request #23
Opened 2024-02-16 10:08 UTC by YaroslavRadevychVynnytskyi

2024-02-16 17:58 UTC, MentorMA requested changes

2024-02-16 17:58 UTC, MentorMA commented on src/main/java/application/bookstore/dto/CreateBookRequestDto.java
> +
No need here empty line

2024-02-16 17:58 UTC, MentorMA commented on src/main/java/application/bookstore/dto/CreateBookRequestDto.java
>      private String description;
I guess you can make validation more detail, you can validate description by size or something else for example

2024-02-17 11:40 UTC, okuzan approved these changes

2024-02-17 11:40 UTC, okuzan commented on src/main/java/application/bookstore/dto/CreateBookRequestDto.java
> +    @Size(min = MIN_DESCRIPTION_LENGTH)
it's ok to use literals here

2024-02-17 14:16 UTC, merged