Added Order model
YaroslavRadevychVynnytskyi/book-store pull request #32
Opened 2024-03-12 13:56 UTC by YaroslavRadevychVynnytskyi

2024-03-12 18:22 UTC, MentorMA requested changes

2024-03-12 18:22 UTC, MentorMA commented on src/main/java/application/bookstore/model/Order.java
> +    }
Tou already have builder and lombok annotations, so you don`t need this anymore

2024-03-13 13:38 UTC, Rommelua requested changes

2024-03-13 13:38 UTC, Rommelua commented on src/main/java/application/bookstore/service/order/OrderService.java
> +    OrderDto placeOrderByUserId(Long id, OrderPlacementRequestDto request);
```suggestion
    OrderDto placeOrderByUserId(Long userId, OrderPlacementRequestDto request);
```

2024-03-13 13:38 UTC, Rommelua commented on src/main/java/application/bookstore/service/order/OrderService.java
> +    List<OrderDto> getOrders(Long id);
userId?

2024-03-13 13:38 UTC, Rommelua commented on src/main/java/application/bookstore/service/order/impl/OrderServiceImpl.java
> +        orderItemRepository.saveAll(savedOrder.getOrderItems());
why don't you use cascade for saving items?

2024-03-13 13:38 UTC, Rommelua commented on src/main/java/application/bookstore/service/order/impl/OrderServiceImpl.java
> +    public OrderDto placeOrderByUserId(Long id, OrderPlacementRequestDto request) {
userId

2024-03-13 13:38 UTC, Rommelua commented on src/main/java/application/bookstore/dto/order/UpdateOrderStatusRequestDto.java
> +public record UpdateOrderStatusRequestDto(String status) {
Why String status? Use enum

2024-03-14 09:14 UTC, Rommelua commented on src/main/java/application/bookstore/dto/order/UpdateOrderStatusRequestDto.java
> +public record UpdateOrderStatusRequestDto(Order.Status status) {
NotNull

2024-03-14 09:14 UTC, Rommelua commented on src/main/java/application/bookstore/service/order/impl/OrderServiceImpl.java
> +        Order savedOrder = orderRepository.save(order);
```suggestion
        order = orderRepository.save(order);
```

2024-03-14 09:36 UTC, merged